<script>
	function tc_bootstrap() {
		(function ($) {
			$(document).ready(function () {
				var application = new Tc.Application($('body'), {});
				application.registerModules();
				application.start();
			});
		})(Tc.$);
	}
	
	Modernizr.load([
		{
			test : Modernizr.json,
			nope : ['/assets/lib/json2.min.js']
		},
		{
			test : Modernizr.localstorage,
			nope : ['/assets/lib/localStorage.js']
		}, {
			
		load: <? if (APP_ENV == 'dev'): ?>"dist/base.js"<? else: ?>"dist/base.min.js"<? endif; ?>,
		complete: tc_bootstrap
	}]);
</script>
